export const environment = {
  production: true,
  contactEmail: 'contact@zine-eddinetoubal.fr',
  contactEmailPerso: 'toubalzineddine77@gmail.com',
  numTelephone: "+33 65 22 26 764",
  siteTitle: 'Zine-Eddine Toubal - Portfolio',
  siteOwner: 'Zine-Eddine Toubal',
  faviconPath: '../../../assets/images/avatar.jpg',
  adresse: "06 Rue du docteur blanche, 76000 Rouen",
  website: "zine-eddinetoubal.fr",
  googleAnalyticsKey: '',
  enableDebug: false,
  cdnUrl: '',
  linkedinUrl: 'https://www.linkedin.com/in/zine-eddine-toubal',
  githubUrl: 'https://github.com/toubal77',
};
