export const environment = {
  production: false,
  contactEmail: 'toubalzineddine77@gmail.com',
  contactEmailPerso: 'toubalzineddine77@gmail.com',
  numTelephone: "+33 65 22 26 764",
  siteTitle: 'Portfolio Dev - Zine-Eddine TOUBAL',
  siteOwner: 'Zine-Eddine TOUBAL',
  faviconPath: '../../../assets/images/avatar.jpg',
  adresse: "06 Rue du docteur blanche, 76000 Rouen",
  website: "zine-eddinetoubal.fr",
  googleAnalyticsKey: '',
  enableDebug: true,
  cdnUrl: 'http://localhost:4200/assets',
  linkedinUrl: 'https://www.linkedin.com/in/zine-eddine-toubal',
  githubUrl: 'https://github.com/toubal77',
};
