name: CI-CD Pipeline

on: 
  push:
    branches: [develop, master]
  pull_request: 
    branches: [develop, master]
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      # recupération du code depuis le depot
      - name: Checkout code
        uses: actions/checkout@v2
    
      # configuration de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '20'

      # installation des dependances
      - name: Install dependencies
        run: npm install

      # execution d'ESLint pour verifier la qualite du code
      - name: Run ESLint
        run: npm run lint

      # Build du projet
      - name: Build the project
        run: |
          if [ $GITHUB_REF = "refs/heads/master" ]; then
            echo "Building for production...";
            npm run build -- --configuration=production;
          else
            echo "Building for development...";
            npm run build;  # Build en développement
          fi

      # Deploy FTP
      - name: Deploy FTP
        if: github.ref == 'refs/heads/master'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.cluster100.hosting.ovh.net
          username: zineedp
          password: Zineddine77Tbl
          local-dir: dist/zine-eddinetoubal/browser/
          server-dir: /www/
